### ISSUE TITLE
NPE while tab complete command in console

### ISSUE THREAD

**Issue by P3ridot** [TitanVale/Titanium#42]
```
[15:19:28 INFO]: Error while finding completion candidates
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "offers" is null
        at net.titanium.console.TitaniumConsoleCompleter.complete(TitaniumConsoleCompleter.java:30) ~[patched_1.8.8.jar:git-Titanium-8]
        at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4381) ~[patched_1.8.8.jar:git-Titanium-8]        at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4347) ~[patched_1.8.8.jar:git-Titanium-8]        at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4286) ~[patched_1.8.8.jar:git-Titanium-8]
        at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3778) [patched_1.8.8.jar:git-Titanium-8]
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:679) [patched_1.8.8.jar:git-Titanium-8]
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468) [patched_1.8.8.jar:git-Titanium-8]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) [patched_1.8.8.jar:git-Titanium-8]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) [patched_1.8.8.jar:git-Titanium-8]
        at net.minecraft.server.v1_8_R3.DedicatedServer$2.run(DedicatedServer.java:75) [patched_1.8.8.jar:git-Titanium-8]
[15:19:29 INFO]: Error while finding completion candidates
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "offers" is null
        at net.titanium.console.TitaniumConsoleCompleter.complete(TitaniumConsoleCompleter.java:30) ~[patched_1.8.8.jar:git-Titanium-8]
        at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4381) ~[patched_1.8.8.jar:git-Titanium-8]        at org.jline.reader.impl.LineReaderImpl.doComplete(LineReaderImpl.java:4347) ~[patched_1.8.8.jar:git-Titanium-8]        at org.jline.reader.impl.LineReaderImpl.expandOrComplete(LineReaderImpl.java:4286) ~[patched_1.8.8.jar:git-Titanium-8]
        at org.jline.reader.impl.LineReaderImpl$1.apply(LineReaderImpl.java:3778) [patched_1.8.8.jar:git-Titanium-8]
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:679) [patched_1.8.8.jar:git-Titanium-8]
        at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468) [patched_1.8.8.jar:git-Titanium-8]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) [patched_1.8.8.jar:git-Titanium-8]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) [patched_1.8.8.jar:git-Titanium-8]
        at net.minecraft.server.v1_8_R3.DedicatedServer$2.run(DedicatedServer.java:75) [patched_1.8.8.jar:git-Titanium-8]
```

**Comment by P3ridot** [comment]
Probably returning empty iterator if there is no tab completes will fix this issue
